name: sugarCulinary
description: A new Flutter project.


publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3 
  hive_flutter: ^1.1.0
  flutter_picker: ^2.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  marmiteur: ^3.0.0
  pubspec_yaml: ^3.1.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.1
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  win32: ^5.7.2

  
  
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

  
  
  
  
  
  flutter_lints: ^3.0.1





flutter:
  
  
  
  uses-material-design: true
  generate: true

  
  assets:
    - recipe_pics/no_image.png
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
